import type { CSSProperties } from "react";

export const PATH_TOKENS = {
  spacing: 8,
  radius: {
    card: 24,
    pill: 9999,
    modal: 24,
  },
  touch: {
    min: 48,
  },
  motion: {
    ui: 180,
    celebration: 600,
  },
  shadow: {
    level1: "0 2px 8px rgba(0,0,0,0.08)",
  },
  node: {
    radius: 9999,
    highlightOpacity: 0.24,
    outerShadow: "0 6px 14px rgba(0,0,0,0.18)",
    activeGlow: "0 0 0 2px rgba(133,226,216,0.42),0 0 16px rgba(77,217,192,0.25)",
    states: {
      done: {
        shell: "#4DD9C0",
        border: "#2FBEA9",
        base: "#4AAE9D",
        icon: "#FFFFFF",
      },
      active: {
        shell: "#FF6B3D",
        border: "#F05E35",
        base: "#D06748",
        icon: "#FFFFFF",
      },
      available: {
        shell: "#DDE4EE",
        border: "#C8D0DB",
        base: "#BCC5D1",
        icon: "#7A8799",
      },
      locked: {
        shell: "#B0B8C4",
        border: "#9FA8B5",
        base: "#9099A6",
        icon: "#6F7D93",
      },
    },
  },
  colors: {
    primary: "#FF6B3D",
    secondary: "#0EA5A4",
    accent: "#FFC857",
    success: "#4DD9C0",
    muted: "#9FB0CA",
    ink: "#1A2D4A",
    surface: "#FFFFFF",
    surfaceAlt: "#F5F8FD",
    pathSurface: "#E9EEF5",
    lock: "#CBD5E1",
  },
} as const;

export const PATH_CSS_VARS: CSSProperties = {
  ["--path-space-1" as string]: `${PATH_TOKENS.spacing}px`,
  ["--path-space-2" as string]: `${PATH_TOKENS.spacing * 2}px`,
  ["--path-space-3" as string]: `${PATH_TOKENS.spacing * 3}px`,
  ["--path-space-4" as string]: `${PATH_TOKENS.spacing * 4}px`,
  ["--path-radius-card" as string]: `${PATH_TOKENS.radius.card}px`,
  ["--path-radius-pill" as string]: `${PATH_TOKENS.radius.pill}px`,
  ["--path-radius-modal" as string]: `${PATH_TOKENS.radius.modal}px`,
  ["--path-touch" as string]: `${PATH_TOKENS.touch.min}px`,
  ["--path-motion-ui" as string]: `${PATH_TOKENS.motion.ui}ms`,
  ["--path-motion-celebration" as string]: `${PATH_TOKENS.motion.celebration}ms`,
  ["--path-shadow-1" as string]: PATH_TOKENS.shadow.level1,
  ["--node-radius-full" as string]: `${PATH_TOKENS.node.radius}px`,
  ["--node-highlight-opacity" as string]: PATH_TOKENS.node.highlightOpacity,
  ["--node-outer-shadow" as string]: PATH_TOKENS.node.outerShadow,
  ["--node-active-glow" as string]: PATH_TOKENS.node.activeGlow,
  ["--node-done-shell" as string]: PATH_TOKENS.node.states.done.shell,
  ["--node-done-border" as string]: PATH_TOKENS.node.states.done.border,
  ["--node-done-base" as string]: PATH_TOKENS.node.states.done.base,
  ["--node-done-icon" as string]: PATH_TOKENS.node.states.done.icon,
  ["--node-active-shell" as string]: PATH_TOKENS.node.states.active.shell,
  ["--node-active-border" as string]: PATH_TOKENS.node.states.active.border,
  ["--node-active-base" as string]: PATH_TOKENS.node.states.active.base,
  ["--node-active-icon" as string]: PATH_TOKENS.node.states.active.icon,
  ["--node-available-shell" as string]: PATH_TOKENS.node.states.available.shell,
  ["--node-available-border" as string]: PATH_TOKENS.node.states.available.border,
  ["--node-available-base" as string]: PATH_TOKENS.node.states.available.base,
  ["--node-available-icon" as string]: PATH_TOKENS.node.states.available.icon,
  ["--node-locked-shell" as string]: PATH_TOKENS.node.states.locked.shell,
  ["--node-locked-border" as string]: PATH_TOKENS.node.states.locked.border,
  ["--node-locked-base" as string]: PATH_TOKENS.node.states.locked.base,
  ["--node-locked-icon" as string]: PATH_TOKENS.node.states.locked.icon,
  ["--path-primary" as string]: PATH_TOKENS.colors.primary,
  ["--path-secondary" as string]: PATH_TOKENS.colors.secondary,
  ["--path-accent" as string]: PATH_TOKENS.colors.accent,
  ["--path-success" as string]: PATH_TOKENS.colors.success,
  ["--path-muted" as string]: PATH_TOKENS.colors.muted,
  ["--path-ink" as string]: PATH_TOKENS.colors.ink,
  ["--path-surface" as string]: PATH_TOKENS.colors.surface,
  ["--path-surface-alt" as string]: PATH_TOKENS.colors.surfaceAlt,
  ["--path-surface-track" as string]: PATH_TOKENS.colors.pathSurface,
  ["--path-lock" as string]: PATH_TOKENS.colors.lock,
};
