"""create mission_templates table

Revision ID: 0020_mission_templates
Revises: 0019_child_last_mission_done_at
Create Date: 2026-02-17 23:10:00
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0020_mission_templates"
down_revision: str | None = "0019_child_last_mission_done_at"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'daily_mission_rarity') THEN
                CREATE TYPE daily_mission_rarity AS ENUM ('normal', 'special', 'epic');
            END IF;
        END
        $$;
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS mission_templates (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id INTEGER NOT NULL REFERENCES tenants(id),
            school_id INTEGER NULL,
            class_id INTEGER NULL,
            title VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            rarity daily_mission_rarity NOT NULL,
            base_xp INTEGER NOT NULL,
            base_coin INTEGER NOT NULL,
            active BOOLEAN NOT NULL DEFAULT true
        );
        """
    )

    op.execute("CREATE INDEX IF NOT EXISTS ix_mission_templates_tenant_id ON mission_templates (tenant_id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_mission_templates_school_id ON mission_templates (school_id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_mission_templates_class_id ON mission_templates (class_id);")

    op.execute(
        """
        DO $$
        BEGIN
            IF to_regclass('public.schools') IS NOT NULL
               AND NOT EXISTS (
                   SELECT 1
                   FROM pg_constraint
                   WHERE conname = 'fk_mission_templates_school_id_schools'
               ) THEN
                ALTER TABLE mission_templates
                ADD CONSTRAINT fk_mission_templates_school_id_schools
                FOREIGN KEY (school_id) REFERENCES schools(id);
            END IF;
        END
        $$;
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF to_regclass('public.classes') IS NOT NULL
               AND NOT EXISTS (
                   SELECT 1
                   FROM pg_constraint
                   WHERE conname = 'fk_mission_templates_class_id_classes'
               ) THEN
                ALTER TABLE mission_templates
                ADD CONSTRAINT fk_mission_templates_class_id_classes
                FOREIGN KEY (class_id) REFERENCES classes(id);
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE IF EXISTS mission_templates
        DROP CONSTRAINT IF EXISTS fk_mission_templates_class_id_classes;
        """
    )
    op.execute(
        """
        ALTER TABLE IF EXISTS mission_templates
        DROP CONSTRAINT IF EXISTS fk_mission_templates_school_id_schools;
        """
    )

    op.execute("DROP INDEX IF EXISTS ix_mission_templates_class_id;")
    op.execute("DROP INDEX IF EXISTS ix_mission_templates_school_id;")
    op.execute("DROP INDEX IF EXISTS ix_mission_templates_tenant_id;")

    op.execute("DROP TABLE IF EXISTS mission_templates;")
